spring:
  security:
    oauth2:
      client:
        registration:
           # this id should be use with the "redirect_url" in keycloak, i.e. {baseUrl}/login/oauth2/code/{registration_key}
           spring-demo-client:
              client-id: oauth-demo-spring-thymeleaf
              client-secret: zxcWAQ9yrQBcTHMTNnvthBWpUtHthkDl
              authorization-grant-type: authorization_code
              scope:
              - openid
              - profile
              - roles
              provider: keycloak
        provider:
          keycloak:
             issuerUri: http://localhost:8180/realms/keycloak-learn
